### ISSUE TITLE
Getting timeout error

### ISSUE THREAD

**Issue by shikha1970** [machine-learning-apps/ml-template-azure#14]
![error](https://user-images.githubusercontent.com/73643137/101876998-59666680-3bb3-11eb-8629-d5fe156fcb25.png)

**Comment by marvinbuss** [comment]
Hi @shikha1970,
Let me test it quickly. Looks like there is some issue with the dependencies. I will test the setup and give you an update later during the day.

**Comment by marvinbuss** [comment]
Hi @shikha1970,
Thanks for submitting the issue. I will fix the issue with the attached PR. Can you please update the environment.yml in `train/` and `deploy/` to the following:

`deploy/environment.yml`
```yaml
# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: deployment_env
dependencies:
  - python=3.6.2
  - scikit-learn=0.23.2
  - numpy=1.19.4
  - pip:
    - azureml-defaults==1.19.0
    - azureml-monitoring==0.1.0a21
    - inference-schema==1.1.0
    - inference-schema[numpy-support]==1.1.0
channels:
  - conda-forge
```

`train/environment.yml`
```yaml
# Conda environment specification. Details about the Conda environment file format:
# https://conda.io/docs/user-guide/tasks/manage-environments.html#create-env-file-manually

name: training_env
dependencies:
  - python=3.6.2
  - scikit-learn=0.23.2
  - pandas=1.1.5
  - matplotlib=3.3.3
  - pip:
    - azureml-defaults==1.19.0
channels:
  - conda-forge
```
